
package ma.enset.client;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws.enset.ma/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.ConvertResponse")
    @Action(input = "http://ws.enset.ma/BanqueService/convertRequest", output = "http://ws.enset.ma/BanqueService/convertResponse")
    public double convert(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<ma.enset.client.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.CompteListResponse")
    @Action(input = "http://ws.enset.ma/BanqueService/compteListRequest", output = "http://ws.enset.ma/BanqueService/compteListResponse")
    public List<Compte> compteList();

    /**
     * 
     * @param code
     * @return
     *     returns ma.enset.client.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompt", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.GetCompt")
    @ResponseWrapper(localName = "getComptResponse", targetNamespace = "http://ws.enset.ma/", className = "ma.enset.client.GetComptResponse")
    @Action(input = "http://ws.enset.ma/BanqueService/getComptRequest", output = "http://ws.enset.ma/BanqueService/getComptResponse")
    public Compte getCompt(
        @WebParam(name = "code", targetNamespace = "")
        int code);

}
